'use client'

import { useState, useEffect, useCallback } from 'react'
import { ReactReader, ReactReaderStyle } from 'react-reader'
import { updateReadingProgress } from '@/app/(app)/book/actions'

interface EpubViewerProps {
  bookId: string
  fileUrl: string
  initialLocation?: string | null
  theme: 'light' | 'dark' | 'sepia'
}

export default function EpubViewer({ bookId, fileUrl, initialLocation, theme }: EpubViewerProps) {
  const [location, setLocation] = useState<string | number>(initialLocation || 0)
  
  // Simple debounce hook logic or timer ref
  useEffect(() => {
    if (!location || location === initialLocation) return

    const timer = setTimeout(() => {
      // EPUB progress percent calculation would normally require total locations generated by rendition.
      // For now, store location hash faithfully and set generic active progress indicator.
      updateReadingProgress(bookId, location.toString(), 0.5).catch(console.error)
    }, 2000)

    return () => clearTimeout(timer)
  }, [location, bookId])

  const onLocationChange = (epubcifi: string) => {
    setLocation(epubcifi)
  }

  return (
    <div className="h-full w-full relative">
      <ReactReader
        url={fileUrl}
        location={location}
        locationChanged={onLocationChange}
        epubOptions={{
          flow: 'scrolled-doc', 
        }}
        getRendition={(rendition) => {
          // Inject styles dynamically to the iframe contents whenever theme changes
          const applyTheme = () => {
            if (theme === 'dark') {
              rendition.themes.register('dark', { body: { background: '#0f172a', color: '#f8fafc' } })
              rendition.themes.select('dark')
            } else if (theme === 'sepia') {
              rendition.themes.register('sepia', { body: { background: '#fbf0d9', color: '#43302b' } })
              rendition.themes.select('sepia')
            } else {
              rendition.themes.register('light', { body: { background: '#ffffff', color: '#0f172a' } })
              rendition.themes.select('light')
            }
          }
          applyTheme()
          
          // Re-apply theme specifically on orientation/location jumps
          rendition.on('relocated', applyTheme)
        }}
      />
    </div>
  )
}
